<?php

/**
 * @file
 * Primary module hooks for Kenny Girls Training module.
 */

/**
 * Implements hook_preprocess_HOOK().
 */
function kenny_girls_training_preprocess_page(&$variables) {
  $current_page = \Drupal::routeMatch()->getParameter('node');
  if ($current_page instanceof \Drupal\node\NodeInterface && $current_page->getType() == 'page') {
    $variables['#attached']['library'][] = 'kenny_girls_training/kenny_girls_script';
  }
}