<?php declare(strict_types = 1);

/**
 * @file
 * Functions to support theming in the kenny theme.
 */

/**
 * Implements hook_preprocess_HOOK().
 */
function kenny_preprocess_page(&$variables) {
    if (\Drupal::routeMatch()->getRouteName() == 'view.taxonomy_term.page_taxonomy') {
      $variables['#attached']['library'][] = 'kenny/kenny_script';
    }

    $node = \Drupal::routeMatch()->getParameter('node');

    $variables['#attached']['library'][] = 'kenny/kenny_filter_date';


}

