<?php

/**
 * @file
 * Primary module hooks for Kenny Tracker module.
 */

use Drupal\Core\Entity\EntityInterface;




/**
 * Implements hook_ENTITY_TYPE_delete() for nodes.
 */
function kenny_tracker_node_delete($node) {
  // Перевірте, чи видаляється вузол типу 'tracker'.
  if ($node->getType() == 'tracker_measurements') {
    // Ваша умова для вузлів типу 'tracker'.
    $tracker_service = \Drupal::service('kenny_tracker.tracker_measurements');
    $uid = \Drupal::currentUser()->id();
    $nid = $node->id();
    $is_track = $tracker_service->isTrack($uid);

    if ($is_track) {
      $tracker_service->deleteTrack($uid, $nid);
    }

  }
}



/**
 * Implements hook_entity_insert().
 */
function kenny_tracker_entity_insert(EntityInterface $entity) {
  if ($entity->bundle() == 'measurements') {
    $uid = $entity->getOwnerId();
    $id = $entity->id();
    $date = $entity->get('field_created')->value;

    // Отримуємо сервіс і викликаємо метод для додавання до "Tracker Measurements".
    $tracker_service = \Drupal::service('kenny_tracker.tracker_measurements');
    $tracker_service->setRelevantMeasurements($entity->id(), $uid, $date);
  }
}